export interface Country {
  code: string
  name: string
  dialCode: string
  flag: string
  iso2: string
}

export const countries: Country[] = [
  { code: 'AF', name: 'Afghanistan', dialCode: '+93', flag: '🇦🇫', iso2: 'AF' },
  { code: 'AL', name: 'Albanie', dialCode: '+355', flag: '🇦🇱', iso2: 'AL' },
  { code: 'DZ', name: 'Algérie', dialCode: '+213', flag: '🇩🇿', iso2: 'DZ' },
  { code: 'AD', name: 'Andorre', dialCode: '+376', flag: '🇦🇩', iso2: 'AD' },
  { code: 'AO', name: 'Angola', dialCode: '+244', flag: '🇦🇴', iso2: 'AO' },
  { code: 'AR', name: 'Argentine', dialCode: '+54', flag: '🇦🇷', iso2: 'AR' },
  { code: 'AM', name: 'Arménie', dialCode: '+374', flag: '🇦🇲', iso2: 'AM' },
  { code: 'AU', name: 'Australie', dialCode: '+61', flag: '🇦🇺', iso2: 'AU' },
  { code: 'AT', name: 'Autriche', dialCode: '+43', flag: '🇦🇹', iso2: 'AT' },
  { code: 'AZ', name: 'Azerbaïdjan', dialCode: '+994', flag: '🇦🇿', iso2: 'AZ' },
  { code: 'BH', name: 'Bahreïn', dialCode: '+973', flag: '🇧🇭', iso2: 'BH' },
  { code: 'BD', name: 'Bangladesh', dialCode: '+880', flag: '🇧🇩', iso2: 'BD' },
  { code: 'BY', name: 'Biélorussie', dialCode: '+375', flag: '🇧🇾', iso2: 'BY' },
  { code: 'BE', name: 'Belgique', dialCode: '+32', flag: '🇧🇪', iso2: 'BE' },
  { code: 'BZ', name: 'Belize', dialCode: '+501', flag: '🇧🇿', iso2: 'BZ' },
  { code: 'BJ', name: 'Bénin', dialCode: '+229', flag: '🇧🇯', iso2: 'BJ' },
  { code: 'BT', name: 'Bhoutan', dialCode: '+975', flag: '🇧🇹', iso2: 'BT' },
  { code: 'BO', name: 'Bolivie', dialCode: '+591', flag: '🇧🇴', iso2: 'BO' },
  { code: 'BA', name: 'Bosnie-Herzégovine', dialCode: '+387', flag: '🇧🇦', iso2: 'BA' },
  { code: 'BW', name: 'Botswana', dialCode: '+267', flag: '🇧🇼', iso2: 'BW' },
  { code: 'BR', name: 'Brésil', dialCode: '+55', flag: '🇧🇷', iso2: 'BR' },
  { code: 'BN', name: 'Brunei', dialCode: '+673', flag: '🇧🇳', iso2: 'BN' },
  { code: 'BG', name: 'Bulgarie', dialCode: '+359', flag: '🇧🇬', iso2: 'BG' },
  { code: 'BF', name: 'Burkina Faso', dialCode: '+226', flag: '🇧🇫', iso2: 'BF' },
  { code: 'BI', name: 'Burundi', dialCode: '+257', flag: '🇧🇮', iso2: 'BI' },
  { code: 'KH', name: 'Cambodge', dialCode: '+855', flag: '🇰🇭', iso2: 'KH' },
  { code: 'CM', name: 'Cameroun', dialCode: '+237', flag: '🇨🇲', iso2: 'CM' },
  { code: 'CA', name: 'Canada', dialCode: '+1', flag: '🇨🇦', iso2: 'CA' },
  { code: 'CV', name: 'Cap-Vert', dialCode: '+238', flag: '🇨🇻', iso2: 'CV' },
  { code: 'CF', name: 'République centrafricaine', dialCode: '+236', flag: '🇨🇫', iso2: 'CF' },
  { code: 'TD', name: 'Tchad', dialCode: '+235', flag: '🇹🇩', iso2: 'TD' },
  { code: 'CL', name: 'Chili', dialCode: '+56', flag: '🇨🇱', iso2: 'CL' },
  { code: 'CN', name: 'Chine', dialCode: '+86', flag: '🇨🇳', iso2: 'CN' },
  { code: 'CO', name: 'Colombie', dialCode: '+57', flag: '🇨🇴', iso2: 'CO' },
  { code: 'KM', name: 'Comores', dialCode: '+269', flag: '🇰🇲', iso2: 'KM' },
  { code: 'CG', name: 'Congo', dialCode: '+242', flag: '🇨🇬', iso2: 'CG' },
  { code: 'CD', name: 'Congo (RDC)', dialCode: '+243', flag: '🇨🇩', iso2: 'CD' },
  { code: 'CR', name: 'Costa Rica', dialCode: '+506', flag: '🇨🇷', iso2: 'CR' },
  { code: 'CI', name: 'Côte d\'Ivoire', dialCode: '+225', flag: '🇨🇮', iso2: 'CI' },
  { code: 'HR', name: 'Croatie', dialCode: '+385', flag: '🇭🇷', iso2: 'HR' },
  { code: 'CU', name: 'Cuba', dialCode: '+53', flag: '🇨🇺', iso2: 'CU' },
  { code: 'CY', name: 'Chypre', dialCode: '+357', flag: '🇨🇾', iso2: 'CY' },
  { code: 'CZ', name: 'République tchèque', dialCode: '+420', flag: '🇨🇿', iso2: 'CZ' },
  { code: 'DK', name: 'Danemark', dialCode: '+45', flag: '🇩🇰', iso2: 'DK' },
  { code: 'DJ', name: 'Djibouti', dialCode: '+253', flag: '🇩🇯', iso2: 'DJ' },
  { code: 'DO', name: 'République dominicaine', dialCode: '+1', flag: '🇩🇴', iso2: 'DO' },
  { code: 'EC', name: 'Équateur', dialCode: '+593', flag: '🇪🇨', iso2: 'EC' },
  { code: 'EG', name: 'Égypte', dialCode: '+20', flag: '🇪🇬', iso2: 'EG' },
  { code: 'SV', name: 'Salvador', dialCode: '+503', flag: '🇸🇻', iso2: 'SV' },
  { code: 'GQ', name: 'Guinée équatoriale', dialCode: '+240', flag: '🇬🇶', iso2: 'GQ' },
  { code: 'ER', name: 'Érythrée', dialCode: '+291', flag: '🇪🇷', iso2: 'ER' },
  { code: 'EE', name: 'Estonie', dialCode: '+372', flag: '🇪🇪', iso2: 'EE' },
  { code: 'ET', name: 'Éthiopie', dialCode: '+251', flag: '🇪🇹', iso2: 'ET' },
  { code: 'FJ', name: 'Fidji', dialCode: '+679', flag: '🇫🇯', iso2: 'FJ' },
  { code: 'FI', name: 'Finlande', dialCode: '+358', flag: '🇫🇮', iso2: 'FI' },
  { code: 'FR', name: 'France', dialCode: '+33', flag: '🇫🇷', iso2: 'FR' },
  { code: 'GA', name: 'Gabon', dialCode: '+241', flag: '🇬🇦', iso2: 'GA' },
  { code: 'GM', name: 'Gambie', dialCode: '+220', flag: '🇬🇲', iso2: 'GM' },
  { code: 'GE', name: 'Géorgie', dialCode: '+995', flag: '🇬🇪', iso2: 'GE' },
  { code: 'DE', name: 'Allemagne', dialCode: '+49', flag: '🇩🇪', iso2: 'DE' },
  { code: 'GH', name: 'Ghana', dialCode: '+233', flag: '🇬🇭', iso2: 'GH' },
  { code: 'GR', name: 'Grèce', dialCode: '+30', flag: '🇬🇷', iso2: 'GR' },
  { code: 'GT', name: 'Guatemala', dialCode: '+502', flag: '🇬🇹', iso2: 'GT' },
  { code: 'GN', name: 'Guinée', dialCode: '+224', flag: '🇬🇳', iso2: 'GN' },
  { code: 'GW', name: 'Guinée-Bissau', dialCode: '+245', flag: '🇬🇼', iso2: 'GW' },
  { code: 'GY', name: 'Guyana', dialCode: '+592', flag: '🇬🇾', iso2: 'GY' },
  { code: 'HT', name: 'Haïti', dialCode: '+509', flag: '🇭🇹', iso2: 'HT' },
  { code: 'HN', name: 'Honduras', dialCode: '+504', flag: '🇭🇳', iso2: 'HN' },
  { code: 'HU', name: 'Hongrie', dialCode: '+36', flag: '🇭🇺', iso2: 'HU' },
  { code: 'IS', name: 'Islande', dialCode: '+354', flag: '🇮🇸', iso2: 'IS' },
  { code: 'IN', name: 'Inde', dialCode: '+91', flag: '🇮🇳', iso2: 'IN' },
  { code: 'ID', name: 'Indonésie', dialCode: '+62', flag: '🇮🇩', iso2: 'ID' },
  { code: 'IR', name: 'Iran', dialCode: '+98', flag: '🇮🇷', iso2: 'IR' },
  { code: 'IQ', name: 'Irak', dialCode: '+964', flag: '🇮🇶', iso2: 'IQ' },
  { code: 'IE', name: 'Irlande', dialCode: '+353', flag: '🇮🇪', iso2: 'IE' },
  { code: 'IL', name: 'Israël', dialCode: '+972', flag: '🇮🇱', iso2: 'IL' },
  { code: 'IT', name: 'Italie', dialCode: '+39', flag: '🇮🇹', iso2: 'IT' },
  { code: 'JM', name: 'Jamaïque', dialCode: '+1', flag: '🇯🇲', iso2: 'JM' },
  { code: 'JP', name: 'Japon', dialCode: '+81', flag: '🇯🇵', iso2: 'JP' },
  { code: 'JO', name: 'Jordanie', dialCode: '+962', flag: '🇯🇴', iso2: 'JO' },
  { code: 'KZ', name: 'Kazakhstan', dialCode: '+7', flag: '🇰🇿', iso2: 'KZ' },
  { code: 'KE', name: 'Kenya', dialCode: '+254', flag: '🇰🇪', iso2: 'KE' },
  { code: 'KW', name: 'Koweït', dialCode: '+965', flag: '🇰🇼', iso2: 'KW' },
  { code: 'KG', name: 'Kirghizistan', dialCode: '+996', flag: '🇰🇬', iso2: 'KG' },
  { code: 'LA', name: 'Laos', dialCode: '+856', flag: '🇱🇦', iso2: 'LA' },
  { code: 'LV', name: 'Lettonie', dialCode: '+371', flag: '🇱🇻', iso2: 'LV' },
  { code: 'LB', name: 'Liban', dialCode: '+961', flag: '🇱🇧', iso2: 'LB' },
  { code: 'LS', name: 'Lesotho', dialCode: '+266', flag: '🇱🇸', iso2: 'LS' },
  { code: 'LR', name: 'Libéria', dialCode: '+231', flag: '🇱🇷', iso2: 'LR' },
  { code: 'LY', name: 'Libye', dialCode: '+218', flag: '🇱🇾', iso2: 'LY' },
  { code: 'LI', name: 'Liechtenstein', dialCode: '+423', flag: '🇱🇮', iso2: 'LI' },
  { code: 'LT', name: 'Lituanie', dialCode: '+370', flag: '🇱🇹', iso2: 'LT' },
  { code: 'LU', name: 'Luxembourg', dialCode: '+352', flag: '🇱🇺', iso2: 'LU' },
  { code: 'MG', name: 'Madagascar', dialCode: '+261', flag: '🇲🇬', iso2: 'MG' },
  { code: 'MW', name: 'Malawi', dialCode: '+265', flag: '🇲🇼', iso2: 'MW' },
  { code: 'MY', name: 'Malaisie', dialCode: '+60', flag: '🇲🇾', iso2: 'MY' },
  { code: 'MV', name: 'Maldives', dialCode: '+960', flag: '🇲🇻', iso2: 'MV' },
  { code: 'ML', name: 'Mali', dialCode: '+223', flag: '🇲🇱', iso2: 'ML' },
  { code: 'MT', name: 'Malte', dialCode: '+356', flag: '🇲🇹', iso2: 'MT' },
  { code: 'MR', name: 'Mauritanie', dialCode: '+222', flag: '🇲🇷', iso2: 'MR' },
  { code: 'MU', name: 'Maurice', dialCode: '+230', flag: '🇲🇺', iso2: 'MU' },
  { code: 'MX', name: 'Mexique', dialCode: '+52', flag: '🇲🇽', iso2: 'MX' },
  { code: 'MD', name: 'Moldavie', dialCode: '+373', flag: '🇲🇩', iso2: 'MD' },
  { code: 'MC', name: 'Monaco', dialCode: '+377', flag: '🇲🇨', iso2: 'MC' },
  { code: 'MN', name: 'Mongolie', dialCode: '+976', flag: '🇲🇳', iso2: 'MN' },
  { code: 'ME', name: 'Monténégro', dialCode: '+382', flag: '🇲🇪', iso2: 'ME' },
  { code: 'MA', name: 'Maroc', dialCode: '+212', flag: '🇲🇦', iso2: 'MA' },
  { code: 'MZ', name: 'Mozambique', dialCode: '+258', flag: '🇲🇿', iso2: 'MZ' },
  { code: 'MM', name: 'Myanmar', dialCode: '+95', flag: '🇲🇲', iso2: 'MM' },
  { code: 'NA', name: 'Namibie', dialCode: '+264', flag: '🇳🇦', iso2: 'NA' },
  { code: 'NP', name: 'Népal', dialCode: '+977', flag: '🇳🇵', iso2: 'NP' },
  { code: 'NL', name: 'Pays-Bas', dialCode: '+31', flag: '🇳🇱', iso2: 'NL' },
  { code: 'NZ', name: 'Nouvelle-Zélande', dialCode: '+64', flag: '🇳🇿', iso2: 'NZ' },
  { code: 'NI', name: 'Nicaragua', dialCode: '+505', flag: '🇳🇮', iso2: 'NI' },
  { code: 'NE', name: 'Niger', dialCode: '+227', flag: '🇳🇪', iso2: 'NE' },
  { code: 'NG', name: 'Nigéria', dialCode: '+234', flag: '🇳🇬', iso2: 'NG' },
  { code: 'KP', name: 'Corée du Nord', dialCode: '+850', flag: '🇰🇵', iso2: 'KP' },
  { code: 'NO', name: 'Norvège', dialCode: '+47', flag: '🇳🇴', iso2: 'NO' },
  { code: 'OM', name: 'Oman', dialCode: '+968', flag: '🇴🇲', iso2: 'OM' },
  { code: 'PK', name: 'Pakistan', dialCode: '+92', flag: '🇵🇰', iso2: 'PK' },
  { code: 'PS', name: 'Palestine', dialCode: '+970', flag: '🇵🇸', iso2: 'PS' },
  { code: 'PA', name: 'Panama', dialCode: '+507', flag: '🇵🇦', iso2: 'PA' },
  { code: 'PG', name: 'Papouasie-Nouvelle-Guinée', dialCode: '+675', flag: '🇵🇬', iso2: 'PG' },
  { code: 'PY', name: 'Paraguay', dialCode: '+595', flag: '🇵🇾', iso2: 'PY' },
  { code: 'PE', name: 'Pérou', dialCode: '+51', flag: '🇵🇪', iso2: 'PE' },
  { code: 'PH', name: 'Philippines', dialCode: '+63', flag: '🇵🇭', iso2: 'PH' },
  { code: 'PL', name: 'Pologne', dialCode: '+48', flag: '🇵🇱', iso2: 'PL' },
  { code: 'PT', name: 'Portugal', dialCode: '+351', flag: '🇵🇹', iso2: 'PT' },
  { code: 'QA', name: 'Qatar', dialCode: '+974', flag: '🇶🇦', iso2: 'QA' },
  { code: 'RO', name: 'Roumanie', dialCode: '+40', flag: '🇷🇴', iso2: 'RO' },
  { code: 'RU', name: 'Russie', dialCode: '+7', flag: '🇷🇺', iso2: 'RU' },
  { code: 'RW', name: 'Rwanda', dialCode: '+250', flag: '🇷🇼', iso2: 'RW' },
  { code: 'SA', name: 'Arabie saoudite', dialCode: '+966', flag: '🇸🇦', iso2: 'SA' },
  { code: 'SN', name: 'Sénégal', dialCode: '+221', flag: '🇸🇳', iso2: 'SN' },
  { code: 'RS', name: 'Serbie', dialCode: '+381', flag: '🇷🇸', iso2: 'RS' },
  { code: 'SC', name: 'Seychelles', dialCode: '+248', flag: '🇸🇨', iso2: 'SC' },
  { code: 'SL', name: 'Sierra Leone', dialCode: '+232', flag: '🇸🇱', iso2: 'SL' },
  { code: 'SG', name: 'Singapour', dialCode: '+65', flag: '🇸🇬', iso2: 'SG' },
  { code: 'SK', name: 'Slovaquie', dialCode: '+421', flag: '🇸🇰', iso2: 'SK' },
  { code: 'SI', name: 'Slovénie', dialCode: '+386', flag: '🇸🇮', iso2: 'SI' },
  { code: 'SO', name: 'Somalie', dialCode: '+252', flag: '🇸🇴', iso2: 'SO' },
  { code: 'ZA', name: 'Afrique du Sud', dialCode: '+27', flag: '🇿🇦', iso2: 'ZA' },
  { code: 'KR', name: 'Corée du Sud', dialCode: '+82', flag: '🇰🇷', iso2: 'KR' },
  { code: 'SS', name: 'Soudan du Sud', dialCode: '+211', flag: '🇸🇸', iso2: 'SS' },
  { code: 'ES', name: 'Espagne', dialCode: '+34', flag: '🇪🇸', iso2: 'ES' },
  { code: 'LK', name: 'Sri Lanka', dialCode: '+94', flag: '🇱🇰', iso2: 'LK' },
  { code: 'SD', name: 'Soudan', dialCode: '+249', flag: '🇸🇩', iso2: 'SD' },
  { code: 'SR', name: 'Suriname', dialCode: '+597', flag: '🇸🇷', iso2: 'SR' },
  { code: 'SE', name: 'Suède', dialCode: '+46', flag: '🇸🇪', iso2: 'SE' },
  { code: 'CH', name: 'Suisse', dialCode: '+41', flag: '🇨🇭', iso2: 'CH' },
  { code: 'SY', name: 'Syrie', dialCode: '+963', flag: '🇸🇾', iso2: 'SY' },
  { code: 'TW', name: 'Taïwan', dialCode: '+886', flag: '🇹🇼', iso2: 'TW' },
  { code: 'TJ', name: 'Tadjikistan', dialCode: '+992', flag: '🇹🇯', iso2: 'TJ' },
  { code: 'TZ', name: 'Tanzanie', dialCode: '+255', flag: '🇹🇿', iso2: 'TZ' },
  { code: 'TH', name: 'Thaïlande', dialCode: '+66', flag: '🇹🇭', iso2: 'TH' },
  { code: 'TG', name: 'Togo', dialCode: '+228', flag: '🇹🇬', iso2: 'TG' },
  { code: 'TT', name: 'Trinité-et-Tobago', dialCode: '+1', flag: '🇹🇹', iso2: 'TT' },
  { code: 'TN', name: 'Tunisie', dialCode: '+216', flag: '🇹🇳', iso2: 'TN' },
  { code: 'TR', name: 'Turquie', dialCode: '+90', flag: '🇹🇷', iso2: 'TR' },
  { code: 'TM', name: 'Turkménistan', dialCode: '+993', flag: '🇹🇲', iso2: 'TM' },
  { code: 'UG', name: 'Ouganda', dialCode: '+256', flag: '🇺🇬', iso2: 'UG' },
  { code: 'UA', name: 'Ukraine', dialCode: '+380', flag: '🇺🇦', iso2: 'UA' },
  { code: 'AE', name: 'Émirats arabes unis', dialCode: '+971', flag: '🇦🇪', iso2: 'AE' },
  { code: 'GB', name: 'Royaume-Uni', dialCode: '+44', flag: '🇬🇧', iso2: 'GB' },
  { code: 'US', name: 'États-Unis', dialCode: '+1', flag: '🇺🇸', iso2: 'US' },
  { code: 'UY', name: 'Uruguay', dialCode: '+598', flag: '🇺🇾', iso2: 'UY' },
  { code: 'UZ', name: 'Ouzbékistan', dialCode: '+998', flag: '🇺🇿', iso2: 'UZ' },
  { code: 'VE', name: 'Venezuela', dialCode: '+58', flag: '🇻🇪', iso2: 'VE' },
  { code: 'VN', name: 'Vietnam', dialCode: '+84', flag: '🇻🇳', iso2: 'VN' },
  { code: 'YE', name: 'Yémen', dialCode: '+967', flag: '🇾🇪', iso2: 'YE' },
  { code: 'ZM', name: 'Zambie', dialCode: '+260', flag: '🇿🇲', iso2: 'ZM' },
  { code: 'ZW', name: 'Zimbabwe', dialCode: '+263', flag: '🇿🇼', iso2: 'ZW' },
]
